name: Build Frontend Container
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/build-and-push-frontend-main.yml
jobs:
  build-and-push-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    
    - name: Login to amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: elexis-b2b-dashboard-frontend
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend --build-arg VITE_API_BASE_URL=https://api.amaxa.elexis.ai
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  # deploy-changes-to-eb:
  #   needs: build-and-push-image
  #   uses: kaamkaaz/saarthi-services/.github/workflows/deploy-to-elastic-beanstalk.yml@main
  #   secrets: inherit
        