name: Build API Gateway Container
on:
  pull_request:
    types:
      - closed
    branches:
      - soltech
    paths:
      - backend/**
      - .github/workflows/build-and-push-backend.yml
jobs:
  build-and-push-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    
    - name: Login to amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: elexis-b2b-dashboard-backend
        IMAGE_TAG: demo
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  deploy-changes-to-eb:
    needs: build-and-push-image
    uses: kaamkaaz/saarthi-services/.github/workflows/deploy-to-elastic-beanstalk.yml@main
    secrets: inherit
        